[build-system]
[tool.setuptools]
py-modules = []

[project]
name = "nn-web"
description = "My machine learning web"
version = "2023.1"
requires-python = ">=3.8"
classifiers = [
    "Framework :: Flask",
    "Programming Language :: Python :: 3",
]
